;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        electric-newline-and-maybe-indent
        indent-new-comment-line
        js2-line-break
        js2-mode-show-node
        js2-tab-properly
        kill-region
        ruby-end-space
        ruby-tools-interpolate
        sh-assignment
        tab-to-tab-stop
        tags-loop-continue
        ))

(setq mc/cmds-to-run-once
      '(
        dabbrev-expand
        end-of-buffer
        eval-print-last-sexp
        indent-for-tab-command
        js2-jump-to-definition
        keyboard-escape-quit
        markdown-outdent-or-delete
        save-some-buffers
        yaml-electric-backspace
        yas/expand
        ))
